name: Test and Build

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testRunnerInAllModes:
    name: Test all modes
    runs-on: ubuntu-latest
    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v1

      # Configure test runner
      - name: Run tests
        id: testRunner
        uses: webbertakken/unity-test-runner@v1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_PROJECT_PATH: /
          TEST_MODE: all

      # Upload artifacts
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}

  build:
    name: Build
    needs: testRunnerInAllModes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - StandaloneOSX
          - StandaloneLinux64
          - WebGL
    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v1

      # Configure builder
      - name: Build project
        uses: webbertakken/unity-builder@v0.11
        with:
          projectPath: /
          unityVersion: 2019.3.2f1
          targetPlatform: ${{ matrix.targetPlatform }}

      # Upload distributables
      - name: Upload Build
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
